"""pyarpes plugin for SpecsLab Prodigy exported .xy files.

Currently, this plugin supports following scenarios:
1. Single scan dispersion modes eV vs phi angle.
2. Single scan magnification modes eV vs x.
3. 3D maps: counts as a function of eV, phi, and a third parameter.

First dimension is always energy. It is stored as a first column of the xy data.

Second dimension "nonenegy" is perpendicular to the energy on the MCP detector,
stored as # NonEnergyOrdinate in each block of the data.
This could be both: angular (phi angle) or spatial (along the slit direction).

Third dimension/parameter could be:
- the deflector shift (psi angle)
- manipulator rotation (theta angle).
- other parameter: the details should be provided in specific end station plugin.
The third dimension is stored with an original name found in xy file (Parameter).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np
import xarray as xr

from arpes.helper import clean_keys

if TYPE_CHECKING:
    from numpy.typing import NDArray

from dataclasses import dataclass


@dataclass
class Axis:
    name: str
    values: NDArray[np.float64]


MAP_DIMENSION = 3
SECOND_DIM_NAME = "nonenergy"
THIRD_DIM_NAME = "parameter"

__all__ = ["load_xy"]


class ProdigyXY:
    """Class for Prodigy exported xy file.

    Args:
        list_from_xy_file(list[str] | None): list form of xy file
            (Path(xy_file).open().readlines())

    Attributes:
        params(dict[str, str | int float]): Measurement Parameters
        axis_info(dict[str, tuple[NDArray, str]]):
        Information about all axes:
        key=d1,d2,d3 (values and name)
        intensity: photemission intensity
    """

    def __init__(self, list_from_xy_file: list[str] | None = None) -> None:
        """Initialize."""
        self.params: dict[str, str | float | int] = {}
        self.axis_info: dict[str, tuple[NDArray[np.float64], str]] = {}
        self.axes: list[Axis]
        self.intensity: NDArray[np.float64]
        if list_from_xy_file is not None:
            self.parse(list_from_xy_file)

    def parse(self, list_from_xy_file: list[str]) -> None:
        """Load and then parse the xy file generated by Prodigy.

        Args:
            list_from_xy_file(list[str]):list form of xy file by readlines()

        """
        # --- split header and data ---
        header_lines = [line.strip() for line in list_from_xy_file if line.startswith("#")]
        raw_data = np.loadtxt(list_from_xy_file, comments="#", dtype=float)

        # --- energy + intensity ---
        energies = raw_data[:, 0]
        intensity = raw_data[:, 1]

        # --- metadata ---
        self.params = _parse_xy_head(header_lines)

        # --- dimensions from header ---
        xy_dims = _parse_xy_dims(header_lines)

        if "scan_mode" in self.params and self.params["scan_mode"] == "SnapshotFAT":
            # dynamic calculation
            n_other = np.prod([len(v) for v in xy_dims.values()]) or 1
            n_energy = len(intensity) // n_other
        else:
            n_energy = int(self.params["values_curve"])

        energy_axis = np.linspace(energies[0], energies[n_energy - 1], n_energy)

        axes: list[Axis] = [Axis("eV", energy_axis)]

        # enforce order: nonenergy first, then others
        if SECOND_DIM_NAME in xy_dims:
            axes.append(Axis(SECOND_DIM_NAME, xy_dims[SECOND_DIM_NAME]))

        for name, values in xy_dims.items():
            if name != SECOND_DIM_NAME:
                axes.append(Axis(name, values))

        self.axes = axes
        sizes = [len(ax.values) for ax in self.axes]

        expected_size = int(np.prod(sizes))
        if intensity.size != expected_size:
            msg = f"Data size mismatch: got {intensity.size}, expected {expected_size}"
            raise ValueError(msg)

        # data stored as: (slowest → fastest) = reversed axes
        shape = list(reversed(sizes))

        arr = intensity.reshape(shape)

        # reorder to (energy, nonenergy, ...)
        self.intensity = np.transpose(arr, tuple(reversed(range(len(shape)))))

    def to_data_array(self, **kwargs: str | float) -> xr.DataArray:
        """Export to Xarray."""
        coords: dict[str, NDArray[np.float64]] = {ax.name: ax.values for ax in self.axes}
        dims = [ax.name for ax in self.axes]

        data_array = xr.DataArray(
            self.intensity,
            coords=coords,
            dims=dims,
            attrs=self.params.copy(),
        )

        data_array.attrs.update(kwargs)
        return data_array

    @property
    def integrated_intensity(self) -> np.float64:
        """Return the integrated intensity."""
        return np.sum(np.array(self.intensity))


def load_xy(
    path_to_file: Path | str,
    **kwargs: str | float,
) -> xr.DataArray:
    """Load and parse the xy data.

    Args:
        path_to_file (Path | str): Path to xy file.
        kwargs (str | int | float): Treated as attrs

    Returns:
        xr.DataArray: pyARPES compatible
    """
    with Path(path_to_file).open(mode="r") as xy_file:
        xy_data: list[str] = xy_file.readlines()
        prodigy_xy = ProdigyXY(xy_data)
        data_array = prodigy_xy.to_data_array()
        for k, v in kwargs.items():
            data_array.attrs[k] = v
        return data_array


def _parse_xy_head(xy_data_params: list[str]) -> dict[str, str | int | float]:
    """Parse Common head part.

    Parameters
    ----------
    xy_data_params : list[str]
        Comment lines, starting with #, of the xy data file

    Returns:
    -------
    dict[str, str | int | float]
        Common head data
    """
    temp_params: dict[str, str | int | float] = {}
    start_ind = 0
    for line in xy_data_params:
        if line.startswith("# Group:"):
            break
        start_ind += 1

    for line in xy_data_params[start_ind:]:
        if line.startswith("# Cycle"):
            break
        key, _, value = line[1:].partition(":")
        temp_params[key.strip()] = _formatted_value(value)

    temp_params = clean_keys(temp_params)
    temp_params["curves_scan"] = int(temp_params["curves_scan"])
    temp_params["values_curve"] = int(temp_params["values_curve"])

    return temp_params


def _parse_xy_dims(xy_data_params: list[str]) -> dict[str, NDArray[np.float64]]:
    """Parse dimensions other than energy from xy header."""
    second_dim: list[float] = []
    second_name: str = SECOND_DIM_NAME

    third_dim: list[float] = []
    third_name: str | None = None

    PARAMETER_RE = re.compile(r'# Parameter:\s"([^"]+).+=\s*(-?\d+\.?\d*)')
    NONENERGY_RE = re.compile(r"# NonEnergyOrdinate:\s+(-?\d+\.?\d*)")

    second_dim_done: bool = False
    for line in xy_data_params:
        # --- third dimension (Parameter) ---
        m = PARAMETER_RE.match(line)
        if m:
            if third_name is None:
                third_name = m.group(1).strip()
            third_dim.append(float(m.group(2)))
            continue

        # --- second dimension (NonEnergyOrdinate) ---
        if not second_dim_done:
            m = NONENERGY_RE.match(line)
            if m:
                value = float(m.group(1))
                second_dim.append(value)

                if len(second_dim) > 1 and value == second_dim[0]:
                    second_dim.pop()
                    second_dim_done = True

    xy_dims: dict[str, NDArray[np.float64]] = {}

    if second_dim:
        xy_dims[second_name] = np.array(second_dim)

    if third_dim:
        xy_dims[third_name or THIRD_DIM_NAME] = np.array(third_dim)

    return clean_keys(xy_dims)


def _formatted_value(value: str) -> float | str:
    """Convert string value to float if possible."""
    value = value.strip()
    try:
        return float(value)
    except ValueError:
        return value
