"""Input support for SpecsLab Prodigy exported .xy files.

Supported data dimensionality:
- 1D: energy only
- 2D: energy vs nonenergy (angle or spatial coordinate)
- 3D: energy vs nonenergy vs parameter

Data model:
- The first column is always energy (eV).
- The second column is intensity.
- Additional dimensions are reconstructed from header metadata:
    * NonEnergyOrdinate → second dimension (if present)
    * Parameter → third dimension (if present)

Notes:
- Energy axis is reconstructed using linspace for numerical stability.
- Dimension names are preserved from the file and normalized later by plugins.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np
import xarray as xr

from arpes.helper import clean_keys

if TYPE_CHECKING:
    from numpy.typing import NDArray

from dataclasses import dataclass


@dataclass
class Axis:
    name: str
    values: NDArray[np.float64]


SECOND_DIM_NAME = "nonenergy"
THIRD_DIM_NAME = "parameter"

NUMBER_RE = r"(?P<value>[+-]?\d+(?:\.\d+)?)"

PARAMETER_RE = re.compile(r'# Parameter: "(?P<name>[^"\[]+)(?: \[[^\]]+\])?" = ' + NUMBER_RE)
NONENERGY_RE = re.compile(r"# NonEnergyOrdinate:\s+" + NUMBER_RE)

__all__ = ["load_xy"]


class ProdigyXY:
    """Parser for Prodigy .xy files.

    Attributes:
        params:
            Measurement metadata parsed from header.
        axes:
            Ordered list of axes (energy first).
        intensity:
            N-dimensional intensity array aligned with axes.
    """

    def __init__(self, list_from_xy_file: list[str] | None = None) -> None:
        """Initialize."""
        self.params: dict[str, str | float | int] = {}
        self.axes: list[Axis]
        self.intensity: NDArray[np.float64]
        if list_from_xy_file is not None:
            self.parse(list_from_xy_file)

    def parse(self, list_from_xy_file: list[str]) -> None:
        """Load and then parse the xy file generated by Prodigy.

        Args:
            list_from_xy_file(list[str]):list form of xy file by readlines()

        """
        # --- split header and data ---
        header_lines = [line.strip() for line in list_from_xy_file if line.startswith("#")]
        data = np.loadtxt(list_from_xy_file, comments="#", dtype=float)

        # --- energy + intensity ---
        energies = data[:, 0]
        flat_intensity = data[:, 1]

        # --- metadata ---
        self.params = _parse_xy_head(header_lines)

        # --- dimensions from header ---
        xy_dims = _parse_xy_dims(header_lines)

        if self.params.get("scan_mode") == "SnapshotFAT":
            # for SnapshotFAT mode the values_curve param is typically 1
            # first calculate the product of all non-energy dimensions (fallback to 1 for 1D case)
            n_other = np.prod([len(v) for v in xy_dims.values()], dtype=np.int64, initial=1).item()
            # then calculate the number of energies
            n_energy = len(flat_intensity) // n_other
        else:
            n_energy = int(self.params["values_curve"])
        energy_axis = np.linspace(energies[0], energies[n_energy - 1], n_energy)

        axes: list[Axis] = [Axis("eV", energy_axis)]

        # enforce order: nonenergy first, then others
        if SECOND_DIM_NAME in xy_dims:
            axes.append(Axis(SECOND_DIM_NAME, xy_dims[SECOND_DIM_NAME]))

        for name, values in xy_dims.items():
            if name != SECOND_DIM_NAME:
                axes.append(Axis(name, values))

        self.axes = axes
        sizes = [ax.values.size for ax in self.axes]

        expected_size = int(np.prod(sizes))
        if flat_intensity.size != expected_size:
            msg = f"Data size mismatch: got {flat_intensity.size}, expected {expected_size}"
            raise ValueError(msg)

        self.intensity = _reshape_intensity(flat_intensity, axes)

    def to_data_array(self, **kwargs: str | float) -> xr.DataArray:
        """Export to xarray DataArray."""
        coords: dict[str, NDArray[np.float64]] = {ax.name: ax.values for ax in self.axes}
        dims = [ax.name for ax in self.axes]

        data_array = xr.DataArray(
            self.intensity,
            coords=coords,
            dims=dims,
            attrs=self.params.copy(),
        )

        data_array.attrs.update(kwargs)
        return data_array

    @property
    def integrated_intensity(self) -> np.float64:
        """Return the integrated intensity."""
        return np.sum(np.array(self.intensity))


def load_xy(
    path_to_file: Path | str,
    **kwargs: str | float,
) -> xr.DataArray:
    """Load and parse the xy data.

    Args:
        path_to_file (Path | str): Path to xy file.
        kwargs (str | int | float): Treated as attrs

    Returns:
        xr.DataArray: pyARPES compatible
    """
    with Path(path_to_file).open(mode="r") as xy_file:
        list_from_xy_file: list[str] = xy_file.readlines()
        prodigy_xy = ProdigyXY(list_from_xy_file)
        return prodigy_xy.to_data_array(**kwargs)


def _parse_xy_head(header_lines: list[str]) -> dict[str, str | int | float]:
    """Parse Common head part."""
    temp_params: dict[str, str | int | float] = {}
    start_ind = 0
    for line in header_lines:
        if line.startswith("# Group:"):
            break
        start_ind += 1

    for line in header_lines[start_ind:]:
        if line.startswith("# Cycle"):
            break
        key, _, value = line[1:].partition(":")
        temp_params[key.strip()] = _formatted_value(value)

    temp_params = clean_keys(temp_params)
    temp_params["curves_scan"] = int(temp_params["curves_scan"])
    temp_params["values_curve"] = int(temp_params["values_curve"])

    return temp_params


def _parse_xy_dims(header_lines: list[str]) -> dict[str, NDArray[np.float64]]:
    """Parse non-energy dimensions from header.

    Returns only dimensions present in the file:
    - no NonEnergyOrdinate → 1D
    - NonEnergyOrdinate only → 2D
    - NonEnergyOrdinate + Parameter → 3D
    """
    second_dim: list[float] = []
    second_name: str = SECOND_DIM_NAME

    third_dim: list[float] = []
    third_name: str | None = None

    second_dim_done: bool = False
    for line in header_lines:
        # --- third dimension (Parameter) ---
        m = PARAMETER_RE.match(line)
        if m:
            if third_name is None:
                third_name = m.group("name")
            third_dim.append(float(m.group("value")))
            continue

        # --- second dimension (NonEnergyOrdinate) ---
        if not second_dim_done:
            m = NONENERGY_RE.match(line)
            if m:
                value = float(m.group("value"))
                second_dim.append(value)
                if len(second_dim) > 1 and np.allclose(value, second_dim[0]):
                    second_dim.pop()
                    second_dim_done = True

    xy_dims: dict[str, NDArray[np.float64]] = {}

    if second_dim:
        xy_dims[second_name] = np.array(second_dim)

    if third_dim:
        xy_dims[third_name or THIRD_DIM_NAME] = np.array(third_dim)

    return clean_keys(xy_dims)


def _reshape_intensity(flat: NDArray[np.float64], axes: list[Axis]) -> NDArray[np.float64]:
    """Reshape flat intensity array into N-dimensional form.

    Data in Prodigy files is stored with fastest-changing axis last.
    This function reshapes and reorders it to match axes order:
    (energy, nonenergy, parameter, ...).
    """
    sizes = [len(ax.values) for ax in axes]
    shape = list(reversed(sizes))
    arr = flat.reshape(shape)
    return np.transpose(arr, tuple(reversed(range(len(shape)))))


def _formatted_value(value: str) -> float | str:
    """Convert string value to float if possible."""
    value = value.strip()
    try:
        return float(value)
    except ValueError:
        return value
