"""IO support for Prodigy-exported Igor Pro ITX.

This module provides tools to parse, load, and export ARPES spectrum data
saved in Igor Pro's ITX format (as exported by Prodigy).
It enables interoperability between Prodigy exports and pyARPES by providing
data structures and functions to convert files to and from `xarray.DataArray`.

Main components:
- `ProdigyItx`: Parser and converter class for Prodigy ITX files.
- `load_itx`, `export_itx`: Functions to load or save single/multiple ITX spectra.
- Internal utilities for header parsing, unit correction, and metadata integration.

Typical usage:
    arr = load_itx("example.itx")
    export_itx("out.itx", arr)
"""

from __future__ import annotations

from logging import DEBUG, INFO
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np
import xarray as xr

from arpes.constants import TWO_DIMENSION
from arpes.debug import setup_logger
from arpes.endstations._helper.prodigy import IgorSetscaleFlag, parse_setscale

if TYPE_CHECKING:
    from numpy.typing import NDArray

__all__ = ["load_itx"]

LOGLEVELS = (DEBUG, INFO)
LOGLEVEL = LOGLEVELS[1]
logger = setup_logger(__name__, LOGLEVEL)


class ProdigyItx:
    """Class for Prodigy exported itx file.

    Args:
        list_style_itx_data(list[str] | None): list form of itx file
            (Path(itx_file).open().readlines())

    Attributes:
        params(dict[str, str | int float]): Measurement Parameters
        pixels(tuple[int, int]): The number of the pixcels of the intensity map.
        axis_info(dict[str, tuple[IgorSetscaleFlag, float, float, str]]): Information of axis
        wavename(str): The name of wave
        intensity(list[list[float]]): Phtoemission intensity
    """

    def __init__(self, list_style_itx_data: list[str] | None = None) -> None:
        """Initialize."""
        self.params: dict[str, str | float] = {}
        self.pixels: tuple[int, ...]
        self.axis_info: dict[str, tuple[IgorSetscaleFlag, float, float, str]] = {}
        self.wavename: str = ""
        self.intensity: NDArray[np.floating]
        if list_style_itx_data is not None:
            self.parse(list_style_itx_data)

    def parse(self, list_style_itx_data: list[str]) -> None:
        """Load and then parse the itx file generated by Prodigy.

        Args:
            list_style_itx_data(list[str]):list form of itx file generated by readlines()

        """
        intensity: list[float] = []
        itx_data = list(map(str.rstrip, list_style_itx_data))
        self.params = _parse_itx_head(itx_data, parse_type=True)
        if itx_data.count("BEGIN") != 1:
            msg = "This itx file contains more than one spectra."
            msg += " Use the itx file that Prodigy exports."
            raise RuntimeError(msg)
        for line in itx_data:
            if line.startswith(("IGOR", "BEGIN", "END")):
                continue
            if line.startswith(("X //", "X Note")):
                continue
            if line.startswith("WAVES/S/N"):
                self.pixels = tuple(int(i) for i in line[11:].split(sep=")")[0].split(sep=","))
                logger.debug(f"self.pixels: {self.pixels}")
                self.wavename = line.split(maxsplit=1)[-1].strip()[1:-1]
                continue
            if line.startswith("X SetScale"):
                tmp = parse_setscale(line)
                self.axis_info[tmp[1]] = (tmp[0], tmp[2], tmp[3], tmp[4])
                logger.debug(f"self.axis_info[{tmp[1]}]: {self.axis_info[tmp[1]]}")
                continue
            intensity.extend(float(i) for i in line.split())
        self.intensity = np.array(intensity)
        logger.debug(f"shape of self.intensity: {self.intensity.shape}")

    def to_dataarray(
        self,
        **kwargs: str | float,
    ) -> xr.DataArray:
        """Export to Xarray.

        Args:
            **kwargs(str | float): Extra arguments. Forward to the attrs of the output xarray.

        Returns:
            xr.DataArray: pyarpess compatibility
        """
        common_attrs: dict[str, str | float] = {
            "spectrum_type": "cut",
            "angle_unit": "deg (theta_y)",
        }
        coords: dict[str, NDArray[np.floating]] = {}
        dims: list[str] = []
        # set angle axis

        axis_defs = {
            "x": ("phi", 0),
            "y": ("eV", 1),
            "z": ("cycle", 2),
            "w": ("ch2", 3),
        }

        for key, (coord, pix) in axis_defs.items():
            if key in self.axis_info:
                coords[coord] = _create_coord(
                    axis_info=self.axis_info[key],
                    pixels=self.pixels[pix],
                )
                dims.append(coord)
        attrs = {**common_attrs, **self.params}
        attrs["enegy_unit"] = self.axis_info["y"][3] if "y" in self.axis_info else ""
        attrs["count_unit"] = self.axis_info["d"][3] if "d" in self.axis_info else ""
        logger.debug(f"dims: {dims}")
        data_array = xr.DataArray(
            data=self.intensity.reshape(_pixel_to_shape(self.pixels)),
            coords=coords,
            dims=dims,
            attrs=attrs,
            name=self.wavename,
        )
        for k, v in kwargs.items():
            data_array.attrs[k] = v
        return data_array

    @property
    def integrated_intensity(self) -> np.floating:
        """Return the integrated intensity."""
        return np.sum(self.intensity)


def _pixel_to_shape(pixel: tuple[int, ...]) -> tuple[int, ...]:
    if len(pixel) == TWO_DIMENSION:
        return pixel
    if len(pixel) == TWO_DIMENSION + 1:
        return pixel[2], pixel[0], pixel[1]
    return pixel[3], pixel[2], pixel[0], pixel[1]


def load_itx(
    path_to_file: Path | str,
    **kwargs: str | float,
) -> xr.DataArray | list[xr.DataArray]:
    """Load and parse the itx data.

    Args:
        path_to_file (Path | str): Path to itx file.
        kwargs (str | int | float): Treated as attrs

    Returns:
        xr.DataArray: pyARPES compatible
    """

    def find_indices(
        list_to_check: list[str],
        str_to_find: str = "",
    ) -> list[int]:
        """Get index of All Occurrences of Element in a Python List.

        Args:
            list_to_check(list[str]): list for check
            str_to_find(str): string to find, default to "".

        Returns:
            list[int]: the list of all indexes.
        """
        return [idx for idx, value in enumerate(list_to_check) if value == str_to_find]

    with Path(path_to_file).open(mode="r", encoding="UTF-8") as itx_file:
        itx_data: list[str] = itx_file.readlines()
        itx_data = list(map(str.rstrip, itx_data))
        if itx_data.count("BEGIN") == 1:
            prodigy_itx = ProdigyItx(itx_data)
            return prodigy_itx.to_dataarray(**kwargs)
        end_index_list = [*find_indices(itx_data, ""), -1]
        slice_list = []
        for i in range(len(end_index_list)):
            if i == 0:
                slice_list.append(slice(0, end_index_list[0]))
            else:
                slice_list.append(slice(end_index_list[i - 1], end_index_list[i]))
        multi_itx_data = []
        for sl in slice_list:
            a_itx_data = ProdigyItx(itx_data[sl]).to_dataarray(**kwargs)
            multi_itx_data.append(a_itx_data)
        return multi_itx_data


def _parse_itx_head(
    itx_data: list[str],
    *,
    parse_type: bool = False,
) -> dict[str, str | int | float]:
    """Parse Common head part.

    Parameters
    ----------
    itx_data : list[str]
        Contents of itx data file (return on readlines())
    parse_type: bool
        if true the type of the value in head part is analyzed.

    Returns:
    -------
    dict[str, str | int | float]
        Common head data
    """
    common_params: dict[str, str | int | float] = {}
    for line in itx_data[1:]:
        if not line.startswith("X //") or line.startswith("X //Acquisition Parameters"):
            continue
        if line.startswith("X //User Comment"):
            common_params = _parse_user_comment(line, common_params)
        elif "=" in line:
            line_data = line[4:].split("=", maxsplit=1)
            common_params[line_data[0].strip()] = line_data[1].strip()
        elif ":" in line:
            line_data = line.split(":", maxsplit=1)
            common_params[line_data[0][4:].strip()] = line_data[1].strip()
    if parse_type:
        common_params = _update_params_by_type(common_params)
    return common_params


def _update_params_by_type(
    common_params: dict[str, str | int | float],
) -> dict[str, str | int | float]:
    """Parse type in common params.

    Helper function to parse the type of the value in common params

    Parameters
    ----------
    common_params: dict[str, str | int | float]
        common params to be parsed

    Returns:
    -------
    dict[str, str | int | float]
        parsed common_params
    """
    for k, v in common_params.items():
        if isinstance(v, str) and v.isdecimal():
            common_params[k] = int(v)
        else:
            try:
                common_params[k] = float(v)
            except ValueError:
                common_params[k] = v
    return common_params


def _parse_user_comment(
    line: str,
    common_params: dict[str, str | int | float],
) -> dict[str, str | int | float]:
    """Parse "USER COMMENT" line.

    Helper function: Treating the USER COMMENT

    Parameters
    ----------
    line: str
        line stringl
    common_params: dict[str, str| int, float]
        common parameters

    Returns:
    -------
    dict[str, str| int|float]
        common parameters including "User COMMENT" information
    """
    user_comment: str = line.split("=", maxsplit=1)[1].strip()
    logger.debug(f"user_comement: {user_comment}")
    common_params["User Comment"] = str(common_params.get("User Comment", "")) + user_comment
    line_data: list[str] = user_comment.split(";")
    for item in line_data:
        if len(item) == 0:
            continue
        if ":" in item:
            key, value = item.split(":", maxsplit=1)
            common_params[key] = value
        else:
            common_params[item] = True
    return common_params


def _create_coord(
    axis_info: tuple[IgorSetscaleFlag, float, float, str],
    pixels: int,
) -> NDArray[np.floating]:
    """Create coordinate array from the axis_info."""
    flag, start, delta_or_end, _ = axis_info
    return flag.set_scale(
        num1=float(start),
        num2=float(delta_or_end),
        pixels=pixels,
    )
