"""Enumerations and utilities for handling ARPES and related spectra.

This module defines enumerations and utility functions for handling different types of ARPES
or related spectra in a standardized way.

Contents:
    - SpectrumType (Enum): Represents different spectrum types (CUT, MAP, HV_MAP, SPEM, XPS, etc.).
      Provides properties like `ndim` and `is_intrinsically_spatial`, and a method
      `reference_plot` for obtaining a reference plot corresponding to the spectrum type.

    - DIM_TO_SPECTRUM_TYPE (dict): Maps tuples of dimension names to SpectrumType values.

    - infer_spectrum_type_from_dims(dims: tuple[str, ...]) -> SpectrumType:
      Infers the appropriate SpectrumType from a given tuple of dimension names.

    - AngleUnit (Enum): Represents angle units (Degrees, Radians).

    - EnergyNotation (Enum): Represents energy reference points (Binding, Final).

Usage:
    >>> from arpes.analysis.spectrum_types import SpectrumType, infer_spectrum_type_from_dims
    >>> SpectrumType.CUT.ndim
    2
    >>> infer_spectrum_type_from_dims(("eV", "phi"))
    <SpectrumType.CUT: 'cut'>

Notes:
    - This module is used throughout ARPES analysis routines to standardize handling
      of spectral data arrays.
    - Reference plots generated by `SpectrumType.reference_plot` rely on an
      `owner` object that implements the expected plotting methods.
"""

from __future__ import annotations

from enum import Enum
from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from pathlib import Path

    import numpy as np
    from _typeshed import Incomplete
    from matplotlib.axes import Axes
    from matplotlib.figure import Figure
    from numpy.typing import NDArray


class SpectrumOwner(Protocol):
    """Protocol representing an object that owns ARPES or related spectra.

    It can provide reference plots for different spectrum types.

    This protocol specifies the methods that `SpectrumType.reference_plot`
    expects to call. Implementing classes should provide ways to generate
    reference plots for standard spectrum types.

    Methods:
        _referenced_scans_for_map_plot(**kwargs): Returns a reference plot for a MAP spectrum.
        _referenced_scans_for_hv_map_plot(**kwargs): Returns a reference plot for an HV_MAP
            spectrum.
        _simple_spectrum_reference_plot(**kwargs): Returns a reference plot for a CUT spectrum.
        _referenced_scans_for_spatial_plot(**kwargs): Returns a reference plot for a UCUT or SPEM
            spectrum.
    """

    def _referenced_scans_for_map_plot(
        self,
        **kwargs: Incomplete,
    ) -> Axes | Path | tuple[Figure, NDArray[np.object_]]: ...
    def _referenced_scans_for_hv_map_plot(
        self,
        **kwargs: Incomplete,
    ) -> Axes | Path | tuple[Figure, NDArray[np.object_]]: ...
    def _simple_spectrum_reference_plot(
        self,
        **kwargs: Incomplete,
    ) -> Axes | Path | tuple[Figure, NDArray[np.object_]]: ...
    def _referenced_scans_for_spatial_plot(
        self,
        **kwargs: Incomplete,
    ) -> Axes | Path | tuple[Figure, NDArray[np.object_]]: ...


class SpectrumType(Enum):
    """Enumeration of spectrum types."""

    CUT = "cut"
    UCUT = "ucut"
    MAP = "map"
    HV_MAP = "hv_map"
    SPEM = "spem"
    XPS = "xps"

    @property
    def ndim(self) -> int:
        """Return the number of dimensions associated with the spectrum type."""
        if self in {self.CUT, self.XPS}:
            return 2
        return 3

    @property
    def is_intrinsically_spatial(self) -> bool:
        """Whether the spectrum type is inherently real-space resolved."""
        return self in {SpectrumType.UCUT, SpectrumType.SPEM}

    def reference_plot(self, owner: SpectrumOwner, **kwargs: Incomplete) -> Figure:
        """Return a reference plot method for this spectrum type.

        The `owner` object must implement the appropriate private plotting methods:

            - `_referenced_scans_for_map_plot` for MAP
            - `_referenced_scans_for_hv_map_plot` for HV_MAP
            - `_simple_spectrum_reference_plot` for CUT
            - `_referenced_scans_for_spatial_plot` for UCUT and SPEM

        Raises:
            NotImplementedError: If no reference plot method is defined for the type.
        """
        handlers = {
            SpectrumType.MAP: owner._referenced_scans_for_map_plot,  # noqa: SLF001
            SpectrumType.HV_MAP: owner._referenced_scans_for_hv_map_plot,  # noqa: SLF001
            SpectrumType.CUT: owner._simple_spectrum_reference_plot,  # noqa: SLF001
            SpectrumType.UCUT: owner._referenced_scans_for_spatial_plot,  # noqa: SLF001
            SpectrumType.SPEM: owner._referenced_scans_for_spatial_plot,  # noqa: SLF001
        }

        try:
            func = handlers[self]
        except KeyError as err:
            msg = f"No reference plot defined for spectrum type {self!r}"
            raise NotImplementedError(msg) from err

        return func(**kwargs)


DIM_TO_SPECTRUM_TYPE: dict[tuple[str, ...], SpectrumType] = {
    ("eV",): SpectrumType.XPS,
    ("eV", "phi"): SpectrumType.CUT,
    ("eV", "phi", "beta"): SpectrumType.MAP,
    ("eV", "phi", "theta"): SpectrumType.MAP,
    ("eV", "hv", "phi"): SpectrumType.HV_MAP,
    ("eV", "kp"): SpectrumType.CUT,
    ("eV", "kx", "ky"): SpectrumType.MAP,
    ("eV", "kp", "kz"): SpectrumType.HV_MAP,
}


def infer_spectrum_type_from_dims(dims: tuple[str, ...]) -> SpectrumType:
    """Infer the spectrum type from a given tuple of dimension names.

    Args:
        dims (tuple[str, ...]): Names of the dimensions of a data array.

    Returns:
        SpectrumType: The corresponding spectrum type.

    Raises:
        ValueError: If the provided dimensions do not correspond to any known spectrum type.

    Examples:
        >>> infer_spectrum_type_from_dims(("eV", "phi"))
        <SpectrumType.CUT: 'cut'>
        >>> infer_spectrum_type_from_dims(("eV", "kx", "ky"))
        <SpectrumType.MAP: 'map'>
    """
    try:
        return DIM_TO_SPECTRUM_TYPE[dims]
    except KeyError as exc:
        msg = f"Unknown spectrum dims: {dims}"
        raise ValueError(msg) from exc


class AngleUnit(Enum):
    """Enumeration of angle units."""

    DEG = "Degrees"
    RAD = "Radians"


class EnergyNotation(Enum):
    """Enumeration of energy reference points."""

    BINDING = "Binding"
    FINAL = "Final"
